events {}

http {
    upstream backend_web {
        server 172.20.0.20:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_web;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}